# Generated by Django 2.2.3 on 2020-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
