# Generated by Django 2.2.3 on 2020-03-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_administrator_password'),
        ('party', '0004_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='attendees',
            field=models.ManyToManyField(to='roles.Customer'),
        ),
    ]
