# Generated by Django 2.2.3 on 2020-03-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_auto_20200309_1350'),
        ('party', '0005_party_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='attendees',
        ),
        migrations.CreateModel(
            name='AttendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PENDING', 'P'), ('ACCEPTED', 'A'), ('REJECTED', 'R')], default='PENDING', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.Customer')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
        ),
    ]
