# Generated by Django 2.2.3 on 2020-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
