# Generated by Django 2.2.3 on 2020-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_administrator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.URLField(default=''),
        ),
    ]
